name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build Project
        run: ./gradlew build

      - name: Publish Release
        id: publish
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar

